services: 
  web: 
    build: .
    command: python /code/django_project/manage.py runserver 0.0.0.0:8000
    ports: 
      - 8000:8000
    volumes: 
      - .:/code
    depends_on:
      - db
  db:
    image: postgres:11
    environment: 
      - "POSTGRES_HOST_AUTH_METHOD=trust"