# Generated by Django 3.1.4 on 2021-01-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='teach',
            field=models.BooleanField(default=False),
        ),
    ]
