# Generated by Django 3.1.4 on 2021-01-09 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillmain',
            name='skill_description',
            field=models.TextField(max_length=300),
        ),
    ]
