# Generated by Django 3.1.4 on 2020-12-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20201224_0828'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_sub_category', models.CharField(max_length=200)),
                ('skill_sub_category_description', models.CharField(max_length=200)),
                ('skill', models.ManyToManyField(to='skills.Skill')),
            ],
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_category', models.CharField(max_length=200)),
                ('skill_category_description', models.CharField(max_length=200)),
                ('skills', models.ManyToManyField(to='skills.Skill')),
            ],
        ),
    ]
