# Generated by Django 3.1.4 on 2020-12-24 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_skillcategory_skillsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillcategory',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='skillsubcategory',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_category',
            field=models.ManyToManyField(to='skills.SkillCategory'),
        ),
        migrations.AddField(
            model_name='skill',
            name='skill_sub_category',
            field=models.ManyToManyField(to='skills.SkillSubCategory'),
        ),
    ]
