# Generated by Django 3.1.4 on 2020-12-30 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0005_auto_20201228_1459'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillMain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('skill_name', models.CharField(max_length=200)),
                ('skill_description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.skillmain')),
                ('user_skill_category', models.ManyToManyField(to='skills.SkillCategory')),
                ('user_skill_sub_category', models.ManyToManyField(to='skills.SkillSubCategory')),
            ],
        ),
    ]
