# Generated by Django 3.1.4 on 2020-12-31 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0006_skillmain_userskill'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('-skill_name',)},
        ),
        migrations.AlterModelOptions(
            name='userskill',
            options={'ordering': ('-user_skill',)},
        ),
        migrations.AlterField(
            model_name='skillcategory',
            name='skill_category',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='skillmain',
            name='skill_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='skillsubcategory',
            name='skill_sub_category',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
