# Generated by Django 3.1.4 on 2020-12-31 10:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('skills', '0007_auto_20201231_1001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userskill',
            unique_together={('author', 'user_skill')},
        ),
    ]
